export const RESTORE_MUTATION = 'RESTORE_MUTATION';

export const RECEIVE_ALL_ANIME = 'RECEIVE_ALL_ANIME';
export const RECEIVE_ANIME = 'RECEIVE_ANIME';
export const CLEAR_ANIME = 'CLEAR_ANIME';
export const RECEIVE_SOURCES = 'RECEIVE_SOURCES';
export const CLEAR_SOURCES = 'CLEAR_SOURCES';

export const REPLACE_LIBRARY = 'REPLACE_LIBRARY';
export const CREATE_LIBRARY_ANIME = 'CREATE_LIBRARY_ANIME';
export const CREATE_LIBRARY_EPISODE = 'CREATE_LIBRARY_EPISODE';
export const UPDATE_LIBRARY_EPISODE = 'UPDATE_LIBRARY_EPISODE';
export const COMPLETE_LIBRARY_EPISODE = 'COMPLETE_LIBRARY_EPISODE';

export const TOGGLE_AUTO_TRACKER = 'TOGGLE_AUTO_TRACKER';
export const TOGGLE_ALWAYS_RESUME = 'TOGGLE_ALWAYS_RESUME';
export const TOGGLE_TRACKING_NOTIFICATIONS = 'TOGGLE_TRACKING_NOTIFICATIONS';
export const TOGGLE_RESUME_NOTIFICATIONS = 'TOGGLE_RESUME_NOTIFICATIONS';
export const TOGGLE_RESUME_EPISODE = 'TOGGLE_RESUME_EPISODE';
export const TOGGLE_DRAWER_OPEN = 'TOGGLE_DRAWER_OPEN';

export const TOGGLE_TITLE_LANG = 'TOGGLE_TITLE_LANG';

export const CHANGE_VOLUME = 'CHANGE_VOLUME';
export const TOGGLE_AUTOPLAY_NEXT = 'TOGGLE_AUTOPLAY_NEXT';
export const TOGGLE_VIDEO_UI = 'TOGGLE_VIDEO_UI';
export const TOGGLE_OVERSIZED_PLAYER = 'TOGGLE_OVERSIZED_PLAYER';

export const RECEIVE_DONATION = 'RECEIVE_DONATION';

export const RECEIVE_MOTD = 'RECEIVE_MOTD';
export const MARK_MOTD_READ = 'MARK_MOTD_READ';

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS';
export const TOGGLE_BROWSER_NOTIFICATIONS = 'TOGGLE_BROWSER_NOTIFICATIONS';

export const BAN_USER = 'BAN_USER';
export const UNBAN_USER = 'UNBAN_USER';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const RECEIVE_USER = 'RECEIVE_USER';
export const USE_TOKEN = 'USE_TOKEN';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';
export const CLEAR_SIGNIN_ERRORS = 'CLEAR_SIGNIN_ERRORS';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const MUTE_USER = 'MUTE_USER';
export const UNMUTE_USER = 'UNMUTE_USER';
