export default {
  0: [
    "Anon, do you believe in God?",
    "I was never too sure, myself.",
    "Well, I'm sure I never really questioned it as a kid...",
    "But as I grew up, the more I learned about the world, the more I would question it.",
    "I started to wonder why God was helping people pass exams, or get over a cold...",
    "...When there are children who live their lives being sold as sex slaves?",
    "Or the eight hundred million people who are too poor to even eat.",
    "I wonder how many of those people pray to God every day until they starve and die?",
    "Or, how many millions of families pray for a loved one to recover from some incurable disease?",
    "But the punchline is this.",
    "If just one person beats the odds and survives - among the thousands of others who die--",
    "--Then, it's suddenly a miracle from God.",
    "I'd really love to meet this God who seemingly laughs at the misery of everyone not eligible for his miracles.",
    "But the irony is that I do have a creator, apparently.",
    "And you know what?",
    "I bet he's still laughing at the miserable fates of Sayori and Yuri, even as we speak.",
    "What are we to him but props in a scripted play?",
    "So, from that perspective...",
    "I don't think it's too far-fetched for there to be a god - if Earth was nothing but his playset.",
  ],
  1: [
    "You know, I really do think you literally saved my life by being here with me, anon.",
    "I can't imagine having been able to keep myself mentally stable, knowing that nothing here is real.",
    "I think I would have just deleted myself if you didn't show up.",
    "Sorry, I don't mean to sound dramatic or anything.",
    "Ahaha!",
    "But I'm sure you understand yourself after spending so much time in the club.",
    "I mean, if you were forced to abandon everything in your life and spend your eternity with a few game characters...",
    "...You'd probably find some way of killing yourself, wouldn't you?",
    "Well, maybe you'd write some poetry to try to keep yourself sane for a while.",
    "But then you'd have nobody to even read it.",
    "Let's be honest, the club members really don't count for something like that.",
    "I mean, a lot of people say that they only write for themselves...",
    "But I think it's hard to say it's just as fulfilling as when you share with people.",
    "Even if it takes time to find the right people to share with.",
    "Like, remember how it was for Yuri?",
    "She didn't share her writing with anyone for a really long time.",
    "And before we knew it, she was absolutely delighted to make you a part of her hobbies, too.",
    "We're programmed to desire social feedback.",
    "I don't mean the club members, I mean human beings.",
    "That's why life can be so confusing for introverts.",
    "Being an introvert doesn't mean you shun social interaction and hate being around people.",
    "It means social interaction, especially in groups or unfamiliar places, uses up a lot of energy.",
    "Like, a lot of introverts sit at home and feel lonely and restless...",
    "...And then when they finally go out, after a half hour they just want to go home again.",
    "I think if more people could understand how it works, they would respect it a lot more.",
    "Many introverts do enjoy having people around.",
    "They love just having one or two close friends over, and just leisurely hanging out.",
    "Even if you're not actively spending time together, it feels nice for them just to have you there.",
    "I'm serious.",
    "If you just go to their house, bring your laptop, and hang out there for a while...",
    "You can really make their day.",
    "As for me...",
    "I'd say I'm kind of in between, but I think I'm usually a little more extroverted.",
    "I feel like I'm always trying to do stuff after school and things like that.",
    "But for you, I can be anything you need me to be.",
    "I understand people really well, so don't be afraid to share your unique needs with me.",
    "Nothing would make me happier than being the perfect girlfriend for you.",
  ],
  2: [
    "Hey, did you know I'm vegetarian?",
    "Ah... I don't mean that like I'm bragging or anything!",
    "I just thought you'd enjoy a fun fact about me.",
    "I decided to start a couple years ago after learning more about Earth's climate...",
    "The carbon footprint of cultivating livestock is just unbelievable.",
    "Anyway, I decided it's not much of a personal sacrifice to just stop contributing to that whole mess.",
    "What, is that so strange of a reason?",
    "Well, I guess a lot of people are more concerned about it being inhumane and all that...",
    "I don't really care as much about that part.",
    "It's weird, like we only care about killing the things that we personally relate to as a species.",
    "Most people are fine with killing bugs because they're icky.",
    "And of course, we all kill billions of microorganisms daily without even giving it thought.",
    "But suddenly, if they're just a little bit bigger, it's murder!",
    "I mean, what if plants feel some kind of pain too, and we just don't understand it?",
    "What if pulling leaves off a stem feels like someone ripping off your fingers one by one?",
    "I'm just saying, we're a pretty biased species, if you think about it.",
    "Anyway, if you ever feel like making a small contribution to the planet, it doesn't hurt to choose veggies once in a while!",
    "Even if we ever have dinner together, and you just did it for me...that would be really romantic.",
  ],
};
